window.CAKGUP_CONFIG = {
  APP_PASSWORD: 'cakgup',
  GAS_URL: 'https://script.google.com/macros/s/AKfycbwAnUNUSxouDzo0PIElIJZ5-TaK831lIGDYfURyGDM9iX8kycIDzwcVDW0Tx13jQMhMLA/exec',
  CHILDREN: [
    { id: 'anak1', name: 'Fatiyyah', school: 'SMA Kelas 2' },
    { id: 'anak2', name: 'Alifah', school: 'SMA Kelas 1' },
    { id: 'anak3', name: 'Fatih', school: 'SMP Kelas 1' }
  ],
  DAILY_TASKS: [
    { child: 'Alifah', title: 'Mencuci baju', load: 4, category: 'Pekerjaan Rumah' },
    { child: 'Fatiyyah', title: 'Mencuci piring', load: 2, category: 'Pekerjaan Rumah' },
    { child: 'Fatiyyah', title: 'Beres-beres', load: 2, category: 'Pekerjaan Rumah', description: 'Tugas bersama, butuh 2 orang.' },
    { child: 'Fatih', title: 'Beres-beres', load: 2, category: 'Pekerjaan Rumah', description: 'Tugas bersama, butuh 2 orang.' },
    { child: 'Fatiyyah', title: 'Menyapu dan mengepel dalam', load: 2, category: 'Pekerjaan Rumah' },
    { child: 'Fatih', title: 'Menyapu dan mengepel luar', load: 1, category: 'Pekerjaan Rumah' },
    { child: 'Alifah', title: 'Menyiram tanaman atas', load: 1, category: 'Pekerjaan Rumah' },
    { child: 'Fatih', title: 'Menyiram tanaman bawah', load: 1, category: 'Pekerjaan Rumah' },
    { child: 'Fatih', title: 'Buang sampah', load: 1, category: 'Pekerjaan Rumah' },
    { child: 'Alifah', title: 'Mengangkat jemuran dan menurunkan baju', load: 1, category: 'Pekerjaan Rumah' },
    { child: 'Fatih', title: 'Memasak nasi', load: 1, category: 'Pekerjaan Rumah' },
    { child: 'Fatiyyah', title: 'Membaca quran', load: 2, category: 'Ibadah/Kedisiplinan' },
    { child: 'Alifah', title: 'Membaca quran', load: 2, category: 'Ibadah/Kedisiplinan' },
    { child: 'Fatih', title: 'Membaca quran', load: 2, category: 'Ibadah/Kedisiplinan' },
    { child: 'Fatiyyah', title: 'Hafalan', load: 2, category: 'Ibadah/Kedisiplinan' },
    { child: 'Alifah', title: 'Hafalan', load: 2, category: 'Ibadah/Kedisiplinan' },
    { child: 'Fatih', title: 'Hafalan', load: 2, category: 'Ibadah/Kedisiplinan' },
    { child: 'Fatiyyah', title: 'Shalat dhuha', load: 2, category: 'Ibadah/Kedisiplinan' },
    { child: 'Alifah', title: 'Shalat dhuha', load: 2, category: 'Ibadah/Kedisiplinan' },
    { child: 'Fatih', title: 'Shalat dhuha', load: 2, category: 'Ibadah/Kedisiplinan' },
    { child: 'Fatiyyah', title: 'Shalat tahajud', load: 2, category: 'Ibadah/Kedisiplinan' },
    { child: 'Alifah', title: 'Shalat tahajud', load: 2, category: 'Ibadah/Kedisiplinan' },
    { child: 'Fatih', title: 'Shalat tahajud', load: 2, category: 'Ibadah/Kedisiplinan' },
    { child: 'Fatiyyah', title: 'Melipat baju', load: 2, category: 'Pekerjaan Rumah' },
    { child: 'Alifah', title: 'Melipat baju', load: 2, category: 'Pekerjaan Rumah' },
    { child: 'Fatih', title: 'Melipat baju', load: 2, category: 'Pekerjaan Rumah' },
    { child: 'Fatiyyah', title: 'Setrika baju', load: 2, category: 'Pekerjaan Rumah' },
    { child: 'Alifah', title: 'Setrika baju', load: 2, category: 'Pekerjaan Rumah' },
    { child: 'Fatih', title: 'Setrika baju', load: 2, category: 'Pekerjaan Rumah' },
    { child: 'Fatiyyah', title: 'Mengerjakan 5 soal SNBT', load: 2, category: 'Belajar' },
    { child: 'Alifah', title: 'Mengerjakan 5 soal STAN', load: 2, category: 'Belajar' },
    { child: 'Fatih', title: "Shalat maghrib dan isya' di masjid", load: 2, category: 'Ibadah/Kedisiplinan' },
    { child: 'Fatih', title: 'Shalat subuh di masjid', load: 3, category: 'Ibadah/Kedisiplinan' }
  ],
  MONTHLY_BILLS: [
    { name: 'SPP Fatih', month: '2026-05', status: 'Sudah Dibayar', note: 'Pendidikan & Sekolah' },
    { name: 'SPP Alifah', month: '2026-05', status: 'Sudah Dibayar', note: 'Pendidikan & Sekolah' },
    { name: 'SPP Fatiyyah', month: '2026-05', status: 'Sudah Dibayar', note: 'Pendidikan & Sekolah' },
    { name: 'Jemputan Fatih', month: '2026-05', status: 'Sudah Dibayar', note: 'Pendidikan & Sekolah' },
    { name: 'Fingermatic Fatih', month: '2026-05', status: 'Belum Dibayar', note: 'Pendidikan & Sekolah' },
    { name: 'Listrik Bekasi', month: '2026-05', status: 'Sudah Dibayar', note: 'Rumah Tangga & Utilitas' },
    { name: 'Biznet', month: '2026-05', status: 'Sudah Dibayar', note: 'Rumah Tangga & Utilitas' },
    { name: 'Satpam', month: '2026-05', status: 'Belum Dibayar', note: 'Rumah Tangga & Utilitas' },
    { name: 'Kartu Kredit BRI', month: '2026-05', status: 'Sudah Dibayar', note: 'Keuangan, Iuran & Lainnya' },
    { name: 'Transfer Bapak', month: '2026-05', status: 'Sudah Dibayar', note: 'Keuangan, Iuran & Lainnya' },
    { name: 'Tahlila Fatih', month: '2026-05', status: 'Sudah Dibayar', note: 'Keuangan, Iuran & Lainnya' },
    { name: 'Iuran Liqo', month: '2026-05', status: 'Sudah Dibayar', note: 'Keuangan, Iuran & Lainnya' },
    { name: 'Transfer Rek Mandiri Dik Nora', month: '2026-05', status: 'Sudah Dibayar', note: 'Keuangan, Iuran & Lainnya' },
    { name: 'Tring Pegadaian', month: '2026-05', status: 'Sudah Dibayar', note: 'Keuangan, Iuran & Lainnya' },
    { name: 'Iuran Bulanan Srandakan', month: '2026-05', status: 'Sudah Dibayar', note: 'Keuangan, Iuran & Lainnya' }
  ]
};
